# Generated by Django 3.2 on 2022-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220804_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('article', 'статья'), ('new', 'новость')], default='статья', max_length=45),
        ),
    ]
